api-server/services/base.go

Although these strings are not passed in by the user and therefore do not result in sql injections

fix: quote sql string

---

dashboard/src/routes.tsx

- update token and url for the self-host papercups.

Update papercups information.

---

.gitignore
DEVELOPMENT.md

Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>
add a quick notes on how to setup admin/devs account for first time spinning up
yatai.

chore: add instruction on first time setup for yatai devs

---

dashboard/src/pages/Deployment/Overview.tsx

Make sure display access endpoint only when deployment running

---

api-server/services/db.go

https://github.com/bentoml/Yatai/issues/261

fix: escaping postgresql password

---

api-server/config/yatai_config.go
api-server/services/db.go
common/consts/env.go

https://github.com/bentoml/Yatai/issues/260

feat: support specify pg sslmode

---

Makefile
api-server/services/image_builder.go

https://github.com/bentoml/Yatai/issues/273

fix: add image tags

---

README.md

Fix and format readme with efm.
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

chore: update links to example folder

---

README.md

Fix and format readme with efm.
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

docs: fixing whitespaces and correct list handling under dropdown

---

scripts/quick-install-yatai.sh

This PR address some SC2100 warning about strings from jq as well as quoting some
variables to prevent globbling and word splitting
This PR also handles a redirection missuse under postgres check scripts that should be
out to fd instead of a file

chore: fix SC2100 and quoting for globbing

---

docs/source/installation/yatai.rst
docs/source/installation/yatai_deployment.rst

Update installation documentation to include `--devel` until 1.0

docs: Update installation documentation to include `--devel` until 1.0

---

helm/yatai/templates/NOTES.txt

fix: https://github.com/bentoml/Yatai/issues/383

fix(helm-chart): env secret name in notes

---

api-server/services/organization.go
docs/source/installation/yatai.rst
scripts/start-dev.sh

https://github.com/bentoml/Yatai/issues/316

feat: s3 client support AWS IAM

---

scripts/quick-install-yatai.sh

Hi, I've met this bug when running `scripts/quick-install-yatai.sh`, but easily solved.

fix: wrong json path for postgresql password

---

docs/source/installation/yatai.rst
scripts/quick-install-yatai.sh

related PR: https://github.com/bentoml/Yatai/pull/401
cc @withsmilo

feat(scripts+doc): fixed postgresql ha version

---

api-server/services/deployment_revision.go

fix: https://github.com/bentoml/Yatai/issues/432

fix(api-server): use correct client to delete bentodeployment resource

---

docs/source/installation/yatai.rst
docs/source/installation/yatai_deployment.rst

fix(doc): k8s version in installation

---

README.md

fix(doc): wrong indent in the example yaml

---

dashboard/src/components/BaseSidebar.tsx
dashboard/src/components/BentoRepositoryListCard.tsx
dashboard/src/components/ModelFlatListCard.tsx
docs/README.md
docs/source/conf.py

Signed-off-by: Frost Ming <me@frostming.com>

doc: Fix broken doc links

---

api-server/routes/routes.go

Signed-off-by: Frost Ming <me@frostming.com>
Hi, @yetone I created this PR to fix this:
https://github.com/bentoml/BentoML/blob/35cd25c043ae5c85c622f99654df6a67dadf6cbb/src/bentoml/_internal/yatai_rest_api_client/yatai.py#L43-L45
We also need to update the client to handle erorrs correctly

feat: map not found error returned by gorm

---

docs/source/concepts/bento_crd.rst

field bentoTag does not exist in specs

fix(docs): bento_crd.rst
